### ISSUE TITLE
Error 500 from httpd

### ISSUE THREAD

**Issue by svdmitrij** [simtechdev/smtk-devbox#11]
When I try to connect to dev site via browser I receive the error 500.
In vagrant box we can see log entries (httpd errors log):
```
[Wed Jul 20 12:26:03 2016] [crit] [client 127.0.0.1] configuration error:  couldn't perform authentication. AuthType not set!: /favicon.ico, referer: http://devsite.smtk.dev/
...
```

CentOS version is **centos6-x64**.

Now I workarounded it by change settings in provision/salt/states/stores/files/etc/httpd/conf.d/default.conf.j2 
```
    <Directory />
        Options -Indexes +MultiViews +FollowSymlinks +SymLinksIfOwnerMatch +IncludesNoExec
        AllowOverride All
        {% if salt['grains.get']('osmajorrelease', '6') >= 7 %}
        #Require all granted
        Order allow,deny
        Allow from all
        {% endif %}
    </Directory>
```
(I commented ```Require all granted``` and add 
```
Order allow,deny
Allow from all
```

lines). 
Then call vagrant reload --provision.

**Comment by gongled** [comment]
@Extor fixed this issue.
