### ISSUE TITLE
Please add privileges for the db user.

### ISSUE THREAD

**Issue by myagk0v** [simtechdev/smtk-devbox#18]
DB user which setted in the settings.yml do not have access from the remote host. Thus phpmyadmin not working

**Comment by gongled** [comment]
I'll never install phpMyAdmin for database management on VM, but I'm totally agree that would be nice to have an external access.

**Comment by gongled** [comment]
Fixed (23e61f3fcde6ba603d97fe4a950858c3bb052c9c).
